### ISSUE TITLE
Error on Ubuntu 13.04

### ISSUE THREAD

**Issue by tobinbradley** [hawx/guard-sass#43]
I'm getting an error when guard starts on Ubuntu 13.04. Other than running guard I'm a total ruby noob and I have no idea what to do. I didn't get any error messages during installation of ruby or any of the gems, and ruby --version yields ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]. After the error message guard doesn't watch/update sass, but livereload and concat seem to be working fine. My only guards being loaded are guard-sass, guard-concat, and guard-livereload. It did work fine on 12.10, and I don't _think_ any Ruby libraries changed versions (it was Ruby 1.9.3 on 12.10 as well).

Here's the guard error message. Any help would be greatly appreciated!

19:44:11 - INFO - Guard uses TerminalTitle to send notifications.
19:44:12 - INFO - Sass [0.50s] main.scss -> main.css

19:44:12 - ERROR - Guard::Sass failed to achieve its &lt;start&gt;, exception was:

> [#2DD022E7B4D9] NoMethodError: undefined method `reload_browser' for nil:NilClass
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-livereload-1.4.0/lib/guard/livereload.rb:36:in`run_on_changes'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-sass-1.0.6/lib/guard/sass.rb:164:in `block in notify'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-sass-1.0.6/lib/guard/sass.rb:162:in`each'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-sass-1.0.6/lib/guard/sass.rb:162:in `notify'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-sass-1.0.6/lib/guard/sass.rb:146:in`run_on_changes'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-sass-1.0.6/lib/guard/sass.rb:97:in `run_all'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-sass-1.0.6/lib/guard/sass.rb:90:in`start'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:99:in `block in run_supervised_task'                                                           
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:97:in`catch'  
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:97:in `run_supervised_task'                                                                    
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:54:in`block (2 levels) in run'  
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:175:in `block (3 levels) in scoped_guards'                                                     
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:173:in`each'  
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:173:in `block (2 levels) in scoped_guards'                                                     
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:172:in`catch'  
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:172:in `block in scoped_guards'                                                                
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:170:in`each'  
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:170:in `scoped_guards'                                                                         
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:53:in`block in run'  
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/lumberjack-1.0.3/lib/lumberjack.rb:27:in `unit_of_work'                                                                        
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/runner.rb:52:in`run'  
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard.rb:192:in `block in start'                                                                               
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard.rb:368:in`block in within_preserved_state'  
> [#2DD022E7B4D9] internal:prelude:10:in `synchronize'                             
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard.rb:365:in`within_preserved_state'  
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard.rb:190:in `start'   
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/lib/guard/cli.rb:110:in`start'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in`invoke_command'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in`start'
> [#2DD022E7B4D9] /var/lib/gems/1.9.1/gems/guard-1.8.0/bin/guard:6:in `<top (required)>'
> [#2DD022E7B4D9] /usr/local/bin/guard:23:in`load'
> [#2DD022E7B4D9] /usr/local/bin/guard:23:in `<main>'
> 19:44:12 - INFO - Guard::Sass has just been fired
> 19:44:12 - INFO - Guard is now watching at '/home/tobin/Dropbox/code/web-template'
> 19:44:12 - INFO - LiveReload is waiting for a browser to connect.
